"""Font x-heights (px of a lowercase "x" at 1000 pt), measured ONCE on 2026-09-28.

Every monospace family in the Arch Nerd Font packages OmaSkins offers (each package downloaded,
measured with ImageMagick and deleted again), plus the two non-Nerd monospace fonts Omarchy ships.
JetBrains Mono (550) is the reference. A font missing here is measured on first use and remembered
(data.font_x_height). Not measurable as monospace: ttf-heavydata-nerd (hidden from Browse).
"""

X_HEIGHTS = {
    "0xProto Nerd Font": 550,
    "0xProto Nerd Font Mono": 550,
    "3270 Nerd Font": 428,
    "3270 Nerd Font Mono": 428,
    "Adwaita Mono": 520,
    "AdwaitaMono Nerd Font": 520,
    "AdwaitaMono Nerd Font Mono": 520,
    "Agave Nerd Font": 501,
    "Agave Nerd Font Mono": 501,
    "AnnotationM Nerd Font": 518,
    "AnnotationM Nerd Font Mono": 518,
    "AnonymicePro Nerd Font": 456,
    "AnonymicePro Nerd Font Mono": 456,
    "AtkynsonMono Nerd Font Mono": 496,
    "AurulentSansM Nerd Font": 530,
    "AurulentSansM Nerd Font Mono": 530,
    "BigBlueTerm437 Nerd Font": 500,
    "BigBlueTerm437 Nerd Font Mono": 500,
    "BigBlueTermPlus Nerd Font": 500,
    "BigBlueTermPlus Nerd Font Mono": 500,
    "BitstromWera Nerd Font": 547,
    "BitstromWera Nerd Font Mono": 547,
    "BlexMono Nerd Font": 516,
    "BlexMono Nerd Font Mono": 516,
    "Cascadia Code": 518,
    "Cascadia Code NF": 518,
    "Cascadia Code PL": 518,
    "Cascadia Mono": 518,
    "Cascadia Mono NF": 518,
    "Cascadia Mono PL": 518,
    "CaskaydiaCove Nerd Font": 518,
    "CaskaydiaCove Nerd Font Mono": 518,
    "CaskaydiaMono Nerd Font": 518,
    "CaskaydiaMono Nerd Font Mono": 518,
    "CodeNewRoman Nerd Font Mono": 491,
    "ComicShannsMono Nerd Font": 496,
    "ComicShannsMono Nerd Font Mono": 496,
    "CommitMono Nerd Font": 540,
    "CommitMono Nerd Font Mono": 540,
    "Cousine Nerd Font": 529,
    "Cousine Nerd Font Mono": 529,
    "D2KodingLigature Nerd Font Mono": 510,
    "DaddyTimeMono Nerd Font Mono": 516,
    "DejaVuSansM Nerd Font": 547,
    "DejaVuSansM Nerd Font Mono": 547,
    "DroidSansM Nerd Font": 537,
    "DroidSansM Nerd Font Mono": 537,
    "EnvyCodeR Nerd Font": 540,
    "EnvyCodeR Nerd Font Mono": 540,
    "FantasqueSansM Nerd Font": 528,
    "FantasqueSansM Nerd Font Mono": 528,
    "FiraCode Nerd Font": 540,
    "FiraCode Nerd Font Mono": 540,
    "FiraMono Nerd Font": 527,
    "FiraMono Nerd Font Mono": 527,
    "GeistMono Nerd Font": 530,
    "GeistMono Nerd Font Mono": 530,
    "GohuFont 11 Nerd Font": 455,
    "GohuFont 11 Nerd Font Mono": 455,
    "GohuFont 14 Nerd Font": 501,
    "GohuFont 14 Nerd Font Mono": 501,
    "GohuFont uni11 Nerd Font Mono": 455,
    "GohuFont uni14 Nerd Font": 501,
    "GohuFont uni14 Nerd Font Mono": 501,
    "GoMono Nerd Font": 531,
    "GoMono Nerd Font Mono": 531,
    "GoogleSansCode Nerd Font": 524,
    "GoogleSansCode Nerd Font Mono": 524,
    "Hack Nerd Font": 547,
    "Hack Nerd Font Mono": 547,
    "Hasklug Nerd Font": 486,
    "Hasklug Nerd Font Mono": 486,
    "Hurmit Nerd Font": 500,
    "Hurmit Nerd Font Mono": 500,
    "iMWritingMono Nerd Font Mono": 516,
    "Inconsolata LGC Nerd Font": 531,
    "Inconsolata LGC Nerd Font Mono": 531,
    "Inconsolata Nerd Font": 457,
    "Inconsolata Nerd Font Mono": 457,
    "InconsolataGo Nerd Font": 457,
    "InconsolataGo Nerd Font Mono": 457,
    "InputMono Nerd Font": 546,
    "IntoneMono Nerd Font": 465,
    "IntoneMono Nerd Font Mono": 465,
    "Iosevka Nerd Font Mono": 520,
    "IosevkaTerm Nerd Font Mono": 520,
    "IosevkaTermSlab Nerd Font Mono": 520,
    "JetBrainsMono Nerd Font": 550,
    "JetBrainsMono Nerd Font Mono": 550,
    "JetBrainsMonoNL Nerd Font": 550,
    "JetBrainsMonoNL Nerd Font Mono": 550,
    "Lekton Nerd Font Mono": 475,
    "Liberation Mono": 529,
    "Lilex Nerd Font": 516,
    "Lilex Nerd Font Mono": 516,
    "LiterationMono Nerd Font": 529,
    "LiterationMono Nerd Font Mono": 529,
    "M+1Code Nerd Font Mono": 520,
    "M+CodeLat50 Nerd Font": 520,
    "M+CodeLat50 Nerd Font Mono": 520,
    "M+CodeLat60 Nerd Font": 520,
    "M+CodeLat60 Nerd Font Mono": 520,
    "MartianMono Nerd Font": 600,
    "MartianMono Nerd Font Mono": 600,
    "MesloLGL Nerd Font": 547,
    "MesloLGL Nerd Font Mono": 547,
    "MesloLGLDZ Nerd Font": 547,
    "MesloLGLDZ Nerd Font Mono": 547,
    "MesloLGM Nerd Font": 547,
    "MesloLGM Nerd Font Mono": 547,
    "MesloLGMDZ Nerd Font": 547,
    "MesloLGMDZ Nerd Font Mono": 547,
    "MesloLGS Nerd Font": 547,
    "MesloLGS Nerd Font Mono": 547,
    "MesloLGSDZ Nerd Font": 547,
    "MesloLGSDZ Nerd Font Mono": 547,
    "Monaspace Argon NF": 514,
    "Monaspace Krypton NF": 514,
    "Monaspace Neon NF": 514,
    "Monaspace Radon NF": 560,
    "Monaspace Xenon NF": 518,
    "MonaspiceAr Nerd Font": 514,
    "MonaspiceAr Nerd Font Mono": 514,
    "MonaspiceKr Nerd Font": 514,
    "MonaspiceKr Nerd Font Mono": 514,
    "MonaspiceNe Nerd Font": 514,
    "MonaspiceNe Nerd Font Mono": 514,
    "MonaspiceRn Nerd Font": 560,
    "MonaspiceRn Nerd Font Mono": 560,
    "MonaspiceXe Nerd Font": 518,
    "MonaspiceXe Nerd Font Mono": 518,
    "Monofur Nerd Font": 438,
    "Monofur Nerd Font Mono": 438,
    "Monoid Nerd Font": 667,
    "Monoid Nerd Font Mono": 667,
    "Mononoki Nerd Font": 489,
    "Mononoki Nerd Font Mono": 489,
    "NotoMono Nerd Font": 537,
    "NotoMono Nerd Font Mono": 537,
    "NotoSansM Nerd Font Mono": 536,
    "OpenDyslexicM Nerd Font Mono": 547,
    "OverpassM Nerd Font Mono": 511,
    "ProFont IIx Nerd Font Mono": 556,
    "ProFontWindows Nerd Font": 417,
    "ProFontWindows Nerd Font Mono": 417,
    "ProggyClean CE Nerd Font": 375,
    "ProggyClean CE Nerd Font Mono": 375,
    "ProggyClean Nerd Font": 375,
    "ProggyClean Nerd Font Mono": 375,
    "ProggyCleanSZ Nerd Font": 375,
    "ProggyCleanSZ Nerd Font Mono": 375,
    "RecMonoCasual Nerd Font": 550,
    "RecMonoCasual Nerd Font Mono": 550,
    "RecMonoDuotone Nerd Font": 533,
    "RecMonoDuotone Nerd Font Mono": 533,
    "RecMonoLinear Nerd Font": 533,
    "RecMonoLinear Nerd Font Mono": 533,
    "RecMonoSmCasual Nerd Font": 541,
    "RecMonoSmCasual Nerd Font Mono": 541,
    "RobotoMono Nerd Font": 529,
    "RobotoMono Nerd Font Mono": 529,
    "SauceCodePro Nerd Font": 486,
    "SauceCodePro Nerd Font Mono": 486,
    "ShureTechMono Nerd Font Mono": 500,
    "SpaceMono Nerd Font": 496,
    "SpaceMono Nerd Font Mono": 496,
    "Terminess Nerd Font": 438,
    "Terminess Nerd Font Mono": 438,
    "UbuntuMono Nerd Font": 464,
    "UbuntuMono Nerd Font Mono": 464,
    "VictorMono Nerd Font": 563,
    "VictorMono Nerd Font Mono": 563,
    "ZedMono Nerd Font Mono": 520,
}
